"""
Subreddit lists according to subject matter

Subjects- Mental health, LOA, Advice, New Age, Others
"""

mentalhealth_subreddits = [
                  'Anxiety',
                  'add',
                  'addiction',
                  'ADHD',
                  "ADHD_partners",
                  "ADHDPartners",
                  "adhdwomen",
                  "adhdmeme",
                  'Anger',
                  'alcoholism',
                  "alcoholicsanonymous",
                  "amiugly",
                  "amIuglyBrutallyHonest",
                  "antidepressants",
                  'anxiety_help',
                  'Anxietyhelp',
                  'anxietysuccess',
                  "AnxiousAttachment",
                  'autism',
                  "AutisticPride",
                  'aspergers',
                  "aspergirls",
                  'ARFID',
                  "AvPD",
                  "abusiverelationships",
                  'behavior',
                  'BingeEatingDisorder',
                  'Bingeeating',
                  'behaviortherapy',
                  'bipolar',
                  "bipolar2",
                  'BipolarReddit',
                  'BipolarSOs',
                  'BodyAcceptance',
                  'BodyDysmorphia',
                  "BorderlinePDisorder",
                  'BPD',
                  "BPDlovedones",
                  'Bullimia',
                  'cfs',
                  'criplingalcoholism',
                  'CPTSD',
                  "CPTSDNextSteps",
                  'depression',
                  'depressed',
                  'depression_help',
                  'disorder',
                  'distractit',
                  "Divorce",
                  'domesticviolence',
                  'downsyndrome',
                  "dpdr",
                  'Dysmorphicdisorder',
                  'EatingDisorderHope',
                  'Eatingdisorders',
                  "EDAnonymous",
                  "EDanonymemes",
                  'emetophobia',
                  "emotionalneglect",
                  'EOOD',
                  'ForeverAlone',
                  'GFD',
                  'helpme',
                  "HealthAnxiety",
                  "iamatotalpieceofshit",
                  'lonely',
                  "MaladaptiveDreaming",
                  'mentalhealth',
                  'mentalillness',
                  'MMFB',
                  'MSTsurvivors',
                  'narcissisticparents',
                   'NarcissisticAbuse',
                  "Needafriend",
                  'neurodiversity',
                  "nosurf",
                  'OCD',
                  'OCPD',
                  'Phobia',
                  'Phobias',
                  'ptsd',
                  'PMDD',
                  "Psychosis",
                  "ROCD",
                  'rapecounseling',
                  'rape',
                  'raisedbynarcissists',
                  'sad',
                  'schizophrenia',
                  'schizoaffective',
                  'selfharm',
                  'selfhelp',
                  'socialanxiety',
                  'socialskills',
                  'survivorsofabuse',
                  "SuicideWatch",
                  "TeenAmIUgly",
                  'tourettes',
                  'upset',
                  'ugly'
]

# loa_subreddits = [
#                 'lawofattraction',
#                  'NevilleGoddard',
#                  'nevillegoddardsp',
#                   "NevilleGoddard2",
#                   "NevilleGAZSP",
#                   "ALLISMIND",
#                   "lawofassumptionlw1505",
#                   "LawofAttractionAdvice",
#                   "manifestationvalley"
# ]
#
# philosophies_subreddits= [
#                 "nihilism",
#                 "stoicism",
#                 "Absurdism",
#                 "Existentialism",
#                 "Pessimism"
# ]
#
# newage_subreddits = [
#                 'Psychic',
#                 'spirituality',
#                 "AstralProjection",
#                   "twinflames",
#                   "astrology",
#                   "witchcraft",
#                   "AskAstrologers",
#                   "awakened",
#                   "tarot",
#                   "JosephMurphy",
#                   "Meditation",
#                   "shiftingrealities",
#                   "Soulnexus",
#                   "ALLISMIND",
#                   "Psychonaut",
#                   "occult",
#                   "astrologyreadings",
#                   "energy_work",
#                   "shrooms",
#                   "Glitch_in_the_Matrix",
#                   "LucidDreaming",
#                   "Dreams",
#                   "Empaths",
#                   "EscapingPrisonPlanet",
#                   "Mediums",
#                   "tarotreadings",
#                   "Tarotpractices",
#                   "magick",
#                   "Paranormal",
#                   "WitchesVsPatriarchy",
#                   "Spells",
#                   "Buddhism"
# ]
#
#
# advice_subreddits = ['AskReddit',
#                     'relationship_advice',
#                      "TrueOffMyChest",
#                      "unpopularopinion",
#                      "offmychest",
#                      "Advice",
#                      "AmItheAsshole",
#                      "AskMen",
#                      "BreakUps",
#                      "dating_advice",
#                      "relationships",
#                      "AskWomen",
#                      "NoStupidQuestions",
#                      "ExNoContact",
#                      "dating",
#                      "UnsentLetters",
#                      "TooAfraidToAsk",
#                      "Vent",
#                      "AMA",
#                      "Tinder",
#                      "AskDocs",
#                      "seduction",
#                      "AskWomenOver30",
#                      "Crushes",
#                      "FemaleDatingStrategy",
#                      "datingoverthirty",
#                      "attachment_theory",
#                      "AnxiousAttachment",
#                      "AmITheDevil",
#                      "TalkTherapy",
#                      "morbidquestions",
#                      "Codependency"
# ]
#
# others_subreddits = ['NoFap',
#                     'Subliminal',
#                     "conspiracy",
#                     "teenagers",
#                     "Semenretention",
#                     "antiwork",
#                     "selfimprovement",
#                     "stopdrinking",
#                     "socialskills",
#                     "infp",
#                     "LSD",
#                     "Entrepreneur",
#                     "Drugs",
#                     "weed",
#                     "intermittentfasting",
#                     "vegan",
#                     "fasting",
#                     "loseit",
#                     "infj",
#                     "DMT",
#                     "LifeProTips",
#                     "DecidingToBeBetter",
#                     "mbti",
#                     "PurplePillDebate",
#                     "intj",
#                     "ENFP",
#                     "howtonotgiveafuck",
#                     "DecidingToBeBetter"
# ]